# Generated by Django 5.2.6 on 2025-09-27 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 9, 27, 16, 15, 49, 279952, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
