# Generated by Django 5.2.6 on 2025-11-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0005_alter_category_options_subcategory'),
        ('recipes', '0005_recipe_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodie_app.subcategory'),
        ),
    ]
